<a href="https://colab.research.google.com/github/khaichiong/meco7312/blob/master/Lecture7_GMM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import numpy as np
from scipy.optimize import minimize_scalar
from numpy.linalg import inv

#Optimal GMM

Vector of moment conditions ${\bf h}(\theta,X)$ such that $E[{\bf h}(\theta,X)] = \vec{0}$

In [293]:
def h(theta,x):
  return np.array([[x - theta/2],
            [x**2 - (theta**2)/3],
            [x**3 - (theta**3)/4]])

GMM criterion function with equal weight (inefficient but consistent):

 $Q(\theta) =  \left(\frac{1}{n}\sum_{i=1}^{n}	{\bf h}(\theta,X_{i})\right)^{T}  \left(\frac{1}{n}\sum_{i=1}^{n}	{\bf h}(\theta,X_{i})\right)$

In [294]:
def Q(theta, data):
  hx=0
  for x_data in data:
    hx += h(theta,x_data)/len(data)
  return np.matmul(np.transpose(hx),hx)[0][0]

Suppose we observe the following data

In [295]:
data = np.array([0.1,0.2,0.6,1.0])

Method of moments estimator:

In [296]:
np.mean(data)*2

0.95

GMM estimator with identity weighting matrix. Minimizing the criterion function

In [297]:
res = minimize_scalar(Q,args = data)

In [298]:
res

     fun: 0.002671444829637783
    nfev: 16
     nit: 12
 success: True
       x: 1.034208326372224

Optimal weighting matrix

In [299]:
theta_hat = res.x
S = 0
for x_data in data: 
  S += np.matmul(h(theta_hat,x_data),np.transpose(h(theta_hat,x_data)))/len(data)
S

array([[0.12864776, 0.13898214, 0.1361055 ],
       [0.13898214, 0.15858498, 0.16144969],
       [0.1361055 , 0.16144969, 0.16877364]])

In [300]:
#np.linalg.pinv(S)
inv(S)

array([[  3837.58885062,  -8138.60069147,   4690.64729066],
       [ -8138.60069147,  17501.47304576, -10178.71687947],
       [  4690.64729066, -10178.71687947,   5960.2186682 ]])

Criterion function of optimal GMM with weighting matrix $W$:

$Q(\theta)  = \left(\frac{1}{n}\sum_{i=1}^{n}	{\bf h}(\theta,X_{i})\right)^{T}  W\left(\frac{1}{n}\sum_{i=1}^{n}	{\bf h}(\theta,X_{i})\right)$

In [301]:
def Q_optimal(theta,data,W):
  hx=0
  for x_data in data:
    hx += h(theta,x_data)/len(data)
  return np.matmul(np.matmul(np.transpose(hx),W),hx)[0][0]

Minimizing the GMM objective function with optimal weighting matrix

In [302]:
res = minimize_scalar(Q_optimal,args=(data,inv(S)))

In [303]:
res

     fun: 0.13244718114744697
    nfev: 20
     nit: 16
 success: True
       x: 1.1331002461152475

More generally, suppose we observe the following data

In [371]:
np.random.seed(2)
data = np.random.uniform(0,2.5,(1000,))

In [372]:
#Method of moments
np.mean(data)*2

2.437033133362619

In [373]:
#GMM with identity weighting matrix
res = minimize_scalar(Q,args = data)
res

     fun: 0.00032783971436775176
    nfev: 16
     nit: 11
 success: True
       x: 2.4516826787282553

In [374]:
#Optimal GMM
theta_hat = res.x
S = 0
for x_data in data: 
  S += np.matmul(h(theta_hat,x_data),np.transpose(h(theta_hat,x_data)))/len(data)
inv(S)

array([[ 196.95151812, -177.57095674,   44.31472848],
       [-177.57095674,  170.80893473,  -44.3797855 ],
       [  44.31472848,  -44.3797855 ,   11.85107908]])

In [375]:
res = minimize_scalar(Q_optimal,args=(data,inv(S)))
res

     fun: 0.008827662683287765
    nfev: 18
     nit: 12
 success: True
       x: 2.5101597133561007

In [73]:
x1 = 0.1
x2 = 0.1
x3 = 1.0
def Q(theta):
  q = (h(theta,x1) + h(theta,x2) + h(theta,x3))/3
  return np.sum(q**2)

In [81]:
Q(1.4)

0.31208177777777757

In [25]:
plt.plot(Q(theta))

0.06885461111111112

In [31]:
theta=0.0
(h(theta,x1) + h(theta,x2) + h(theta,x3))/3

array([[0.4  ],
       [0.34 ],
       [0.334]])

In [32]:
theta=1.0
(h(theta,x1) + h(theta,x2) + h(theta,x3))/3

array([[-0.1       ],
       [ 0.00666667],
       [-0.416     ]])

In [34]:
0.334 - 1.0/4

0.08400000000000002